### PR TITLE
Remap IDs script

### PR DESCRIPTION
**Pull request by curlup**
New tool that is intended to rewrite all study files with new IDs based on the patient/sample ID maps. The files in the source directory must be in cBioPortal's standard [file formats](https://docs.cbioportal.org/5.1-data-loading/data-loading/file-formats).

### CODE REVIEW

**Comment by rmadupuri** [comment]
Hi @curlup, this looks great! One quick comment though, would you be able add an option to similar to `--drop-unknown` to include the unknown cases as is? I think this option would be helpful in cases where we only want a subset of the IDs to be updated. 
Thanks!

**Comment by rmadupuri** [comment]
Thanks @curlup, I think that makes sense!

Another question, I am testing the run and I get the below exception.
```
Traceback (most recent call last):
  File "/Users/madupurr/Desktop/test_remap/remap.py", line 300, in <module>
    main()
  File "/Users/madupurr/Desktop/test_remap/remap.py", line 27, in main
    rewrite_study(args.source_path, args.dest_path, patient_map=pmap, sample_map=smap, strict=not args.drop_unknown)
  File "/Users/madupurr/Desktop/test_remap/remap.py", line 69, in rewrite_study
    raise Exception("Not implemented for id/chrom file type {}".format(fname))
Exception: Not implemented for id/chrom file type data_cna_hg19.seg
```

**Comment by curlup** [comment]
Yeah, it's not implemented! =) 
Im not familiar with all cBP formats - does that .seg even can have ids in it? Or should it just in general be skipped? 
(Just as a context i think subset and other scripts also potentially dont support all the file types, they just ignore the ones they dont support i think)

**Comment by rmadupuri** [comment]
@curlup, here's a reference to the different data types cBioPortal supports currently https://github.com/cBioPortal/datahub/blob/master/docs/recommended_staging_filenames.md and the detailed file formats https://docs.cbioportal.org/file-formats/.

Merging your tool for now as it looks great! We can expand on the missing files sometime soon.

**Review by rmadupuri — APPROVED** [review]

**Pull request merged**
