### PR TITLE
Updated meta file generation script

### PR DESCRIPTION
**Pull request by sbabyanusha**

### CODE REVIEW

**Review by rmadupuri — CHANGES_REQUESTED** [review]
Looks great Anusha! 

Two things:
1. Can you write the meta files to the study directory
2. Why do we need an additional command line option for generating the meta file for cna seg?

**Comment by sbabyanusha** [comment]
> Looks great Anusha!
> 
> Three things:
> 
> 1. Can you write the meta files to the study directory

> 2. Why do we need an additional command line option for generating the meta file for cna seg?
> 3. The meta data is hardcoded to a dictionary in the script itself. Can you add/read the meta data from a tab delimited file?

**Comment by sbabyanusha** [comment]
1. I have updated the script to write the files into the study directory.
2. the script couldn't recognize the .seg file so I have added an additional command line option for it.
3. Working on this.

**Comment by rmadupuri** [comment]
Thanks! Minor things,
1. meta_study.txt is not generated
2. when I dont pass any arguments, as in just run `python generate_meta_files.py` it throws an error. Should print the help statement.

**Review by rmadupuri — APPROVED** [review]

**Pull request merged**
